### PR TITLE
WS2-1747 add alpha filter field and component update

### PR DESCRIPTION
**Pull request by mlsamuelson**
### Description

Add "Disable alphabetical filter" field to Web Directory block. Wire up to props.

Why do as "Disable" field when the prop is a boolean `alphaFilter` field? Because it simplified handling of defaulting the filter to enabled even for existing blocks. They won't have the field, but since the missing value will be handled the same as a disable value of FALSE, then everywhere it's missing defaults to enabled.

### Links

- [JIRA ticket](https://asudev.jira.com/browse/WS2-1747)

### Checklist

- [x] Design updates match [Web Standards](https://xd.adobe.com/view/56f6cb78-9af5-4b12-b4ce-ef319f71113f-03a5/) and [Unity Design System](https://unity.web.asu.edu)
- [x] Solution is documented on the Jira ticket
- [x] QA steps to verify have been included on the Jira ticket
- [x] No new PHP or JS errors
- [x] No accessibility issues are introduced with this update
- [x] Added/updated README.md files, if relevant

### Verified in browsers 

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### CODE REVIEW

**Comment by mlsamuelson** [comment]
To be checked on PR multidev:
- [ ] On my local I was seeing the right advance icon on the alpha filters never dismissing, and that resulted in the Z never being clickable.
- [ ] On my local, I ran into an issue I couldn't reproduce in the Unity static reference: for a Faculty Rank Web Directory listing, switching tabs causes all the tabs to disappear and throws an error in the console. Perhaps `components-core` needs to be updated, too...

**Comment by mlsamuelson** [comment]
`components-core` update wasn't the solution to issue 2.

**Comment by mlsamuelson** [comment]
[Visit Site](https://pr-198-webspark-ci.pantheonsite.io/)

Created multidev environment [pr-198](https://dashboard.pantheon.io/sites/aec2f75f-35eb-41f8-abe7-95b292415259#pr-198) for webspark-ci.

**Comment by mlsamuelson** [comment]
All the issues I noted are resolved with the updated `unity-base-theme` and `app-webdir-ui`. Since `components-core` was updated along with those, I've updated it in WS2 as well, however it should be packaged in `app-webdir-ui` for this current issue on hand, so that wasn't really necessary. Just keeping things up to date.

**Review by tbutterf — APPROVED** [review]
This looks good to me.

**Pull request merged**
