### PR TITLE
WS2-2190: Add grid view option to Web Directory

### PR DESCRIPTION
**Pull request by bebaps**
### Description

> NOTE: This PR should be merged in after #674 so the hook order is correct.

This PR adds the grid view option into the Web Directory module.

### Links

- [JIRA ticket](https://asudev.jira.com/browse/WS2-2190)

### Checklist

- [ ] Design updates match [Web Standards](https://xd.adobe.com/view/56f6cb78-9af5-4b12-b4ce-ef319f71113f-03a5/) and [Unity Design System](https://unity.web.asu.edu)
- [ ] Solution is documented on the Jira ticket
- [ ] QA steps to verify have been included on the Jira ticket
- [ ] No new PHP or JS errors
- [ ] No accessibility issues are introduced with this update
- [ ] Added/updated README.md files, if relevant
- [ ] Confirm that any yaml files included have a matching update hook

### Verified in browsers 

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### CODE REVIEW

**Comment by mlsamuelson** [comment]
[Visit Site](https://pr-676-webspark-ci.pantheonsite.io/)

Created multidev environment [pr-676](https://dashboard.pantheon.io/sites/aec2f75f-35eb-41f8-abe7-95b292415259#pr-676) for webspark-ci.

**Comment by tbutterf** [comment]
It looks like there is a CSS problem. The profiles are not displaying correctly in Grid View. The headshot should be on top, but it is still on the left. Also, there is a margin/padding issue with the icons, and they are black, but in storybook they are maroon.

**Comment by bebaps** [comment]
@tbutterf @davidornelas11 updated the theme to add the latest Unity Bootstrap Theme version. Ready to re-review once the site rebuilds.

**Review by tbutterf — APPROVED** [review]
This looks good!

**Pull request merged**
