### PR TITLE
WS2-1643: Overwrite padding properties in .uds-card-arrangement

### PR DESCRIPTION
**Pull request by juanmitriatti**
### Description

Cards have inconsistent padding; header vs. no header, icon vs. no icon.

Solution:
Overwrite padding properties for card and card-header classes.
Overwrite margin-top properties for card-icon-top.
All the overwrite only used into the uds-card-arrangement class.

### Links

- [JIRA ticket](https://asudev.jira.com/browse/WS2-1643)

### Checklist

- [ ] Design updates match [Web Standards](https://xd.adobe.com/view/56f6cb78-9af5-4b12-b4ce-ef319f71113f-03a5/) and [Unity Design System](https://unity.web.asu.edu)
- [ ] Solution is documented on the Jira ticket
- [ ] QA steps to verify have been included on the Jira ticket
- [ ] No new PHP or JS errors
- [ ] No accessibility issues are introduced with this update
- [ ] Added/updated README.md files, if relevant

### Verified in browsers 

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Screenshots

Note: Sections that are not applicable for this issue can be removed.

### CODE REVIEW

**Comment by mlsamuelson** [comment]
[Visit Site](https://pr-192-webspark-ci.pantheonsite.io/)

Created multidev environment [pr-192](https://dashboard.pantheon.io/sites/aec2f75f-35eb-41f8-abe7-95b292415259#pr-192) for webspark-ci.

**Review by bebaps — CHANGES_REQUESTED** [review]
The `padding-top` is adding unwanted padding, very visible when the card has an image. See: https://pr-192-webspark-ci.pantheonsite.io/card-arrangement.

Also, this is another ticket that may be better to be fixed on the UDS side. Although WS2 adds the `card-wrapper`, there is nothing in the UDS CSS that targets a card in such a specific way. Finally, comparing the markup in WS2 to the markup in storybook, they do not match.

**Comment by juanmitriatti** [comment]
Hello @bebaps 
Yes, I was just working on that. I did realize of that behavior after pushing the PR. Let me please check on that.

**Comment by bebaps** [comment]
@juanmitriatti I left a comment on the JIRA ticket, but I must have missed bringing in the updated BS5 markup. Looking at Storybook. Some of these issues have already been resolved on the UDS side. We should bring in the updated markup first, then see if anything still needs to be done on the WS2 side.

**Comment by juanmitriatti** [comment]
@bebaps  Should I check on this page to see if this still needs to be fixed ?
https://unity.web.asu.edu/@asu/unity-bootstrap-theme/index.html?path=/story/get-started-get-started--page
Thanks

**Comment by mlsamuelson** [comment]
@bebaps @juanmitriatti I’d like to discuss this one post-scrum. That will allow us to all get aligned as efficiently as possible on the issue and our path forward for resolving it.

Card Arrangements are kind of a funny creature in WS2 - they launch multiple React card instances, pulling from the components-core library, and so the implementation in WS2 is unique to that platform. 

In post-scrum, we can take a look at the issues here and decide where best to address them.

**Comment by mlsamuelson** [comment]
@chill5-0 Heads-up. Because of your experience working with Card Arrangements, I'd love to have your perspective present when we post-scrum.

**Comment by mlsamuelson** [comment]
I have created https://asudev.jira.com/browse/UDS-1497 so that UDS can take a look at resolving issues upstream. Let's hold on this PR until we have determined if any changes are needed in WS2.

**Review by mlsamuelson — APPROVED** [review]

**Pull request merged**
