### PR TITLE
WS2-1834: Media Library: Add cropped image round option

### PR DESCRIPTION
**Pull request by juanmitriatti**
#### Solution 
Added classes and functionality to remove rounded image border

### Links

- [JIRA ticket](https://asudev.jira.com/browse/WS2-1834)

### Checklist

- [ ] Design updates match [Web Standards](https://xd.adobe.com/view/56f6cb78-9af5-4b12-b4ce-ef319f71113f-03a5/) and [Unity Design System](https://unity.web.asu.edu)
- [ ] Solution is documented on the Jira ticket
- [ ] QA steps to verify have been included on the Jira ticket
- [ ] No new PHP or JS errors
- [ ] No accessibility issues are introduced with this update
- [ ] Added/updated README.md files, if relevant

### Verified in browsers 

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Screenshots

Note: Sections that are not applicable for this issue can be removed.

### CODE REVIEW

**Comment by mlsamuelson** [comment]
[Visit Site](https://pr-393-webspark-ci.pantheonsite.io/)

Created multidev environment [pr-393](https://dashboard.pantheon.io/sites/aec2f75f-35eb-41f8-abe7-95b292415259#pr-393) for webspark-ci.

**Review by mlsamuelson — CHANGES_REQUESTED** [review]
Are we missing some styles here? I'm not seeing the rounding happen with the drop shadow: https://pr-393-webspark-ci.ws.asu.edu/image

**Comment by juanmitriatti** [comment]
> Are we missing some styles here? I'm not seeing the rounding happen with the drop shadow: https://pr-393-webspark-ci.ws.asu.edu/image

Hi Michael,
Good morning
I understood that users shouldn't opt for the shadow option when they've selected the rounded image, right? Wasn't that what we discussed last Friday? Sorry if I misunderstood.

**Comment by mlsamuelson** [comment]
@juanmitriatti I checked my memory with @tbutterf  [in Slack](https://asu-tech.slack.com/archives/CL512LPAT/p1714155923756149) and we determined that the shadow should be usable on both rounded and not rounded, and the shadow should match the shape.

**Comment by juanmitriatti** [comment]
Hi @mlsamuelson 
I was just double checking. I do see the shadow here : https://pr-393-webspark-ci.ws.asu.edu/image .  Is there something wrong there ?
Thanks

**Review by mlsamuelson — APPROVED** [review]

**Pull request merged**
