### PR TITLE
WS2-1577: From JSM - Webspark 2 - Image And Text Block (asu about locations)

### PR DESCRIPTION
**Pull request by juanmitriatti**
### Description

When you add 2 buttons they sit right on top of each other. There is missing padding in between them.

Solution: Adding css styles to introduce spacing between buttons.

### Links

- [JIRA ticket](https://asudev.jira.com/browse/WS2-1577)

### Checklist

- [ ] Design updates match [Web Standards](https://xd.adobe.com/view/56f6cb78-9af5-4b12-b4ce-ef319f71113f-03a5/) and [Unity Design System](https://unity.web.asu.edu)
- [ ] Solution is documented on the Jira ticket
- [ ] QA steps to verify have been included on the Jira ticket
- [ ] No new PHP or JS errors
- [ ] No accessibility issues are introduced with this update
- [ ] Added/updated README.md files, if relevant

### Verified in browsers 

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### CODE REVIEW

**Comment by mlsamuelson** [comment]
[Visit Site](https://pr-84-webspark-ci.pantheonsite.io/)

Created multidev environment [pr-84](https://dashboard.pantheon.io/sites/aec2f75f-35eb-41f8-abe7-95b292415259#pr-84) for webspark-ci.

**Comment by bebaps** [comment]
Reviewed, but leaving this on hold for the moment until further clarification is received.

**Review by bebaps — CHANGES_REQUESTED** [review]
Hi @juanmitriatti, Itzel has verified the functionality for this block, so I have some requests:

1. Please remove the CSS that overrides the `col-md-6` class, and any other CSS that may provide an override.
2. In its place, please explore the use of variable column widths in the blocks' template, as this may provide the most straight forward solution.

Please see the original JIRA ticket for why these changes are being requested, and the Bootstrap variable column widths can be found here: https://getbootstrap.com/docs/4.3/layout/grid/#variable-width-content

**Review by bebaps — APPROVED** [review]
Reviewed updated PR on desktop and mobile device, with short and long text for the buttons. Looks good!

**Pull request merged**
