### PR TITLE
WS2-1767: Update Image and Text CSS to match Storybook

### PR DESCRIPTION
**Pull request by bebaps**
### Description

The Image and Text component CSS does not match Storybook after the BS5 update. This PR brings the code into alignment.

### Links

- [JIRA ticket](https://asudev.jira.com/browse/WS2-1767)

### Checklist

- Design updates match [Web Standards](https://xd.adobe.com/view/56f6cb78-9af5-4b12-b4ce-ef319f71113f-03a5/) and [Unity Design System](https://unity.web.asu.edu)
- Solution is documented on the Jira ticket
- QA steps to verify have been included on the Jira ticket
- No new PHP or JS errors
- No accessibility issues are introduced with this update

### Verified in browsers 

- Chrome
- Safari
- Firefox

### CODE REVIEW

**Comment by mlsamuelson** [comment]
[Visit Site](https://pr-154-webspark-ci.pantheonsite.io/)

Created multidev environment [pr-154](https://dashboard.pantheon.io/sites/aec2f75f-35eb-41f8-abe7-95b292415259#pr-154) for webspark-ci.

**Comment by mlsamuelson** [comment]
To be addressed in UDS via
https://github.com/ASU/asu-unity-stack/pull/1163
https://asudev.jira.com/browse/UDS-1478 
(I'd be fine with this branch and PR being repurposed to pull those updates into WS2).

**Comment by mlsamuelson** [comment]
`unity-bootstrap-theme` release 1.6.4 (when it's published) will contain the fix to remove the max-height. The other styles that are needed for WS2 can stay in here and if they should be fixes upstream in UDS, let's handle removing them from WS2 and moving them to UDS in another ticket that doesn't need to be handled in this release.

**Review by mlsamuelson — DISMISSED** [review]
See previous comment about bringing in the latest `unity-bootstrap-theme` release to resolve the max-height issue.

**Comment by bebaps** [comment]
@mlsamuelson fixed merge conflict, and updated UDS to 1.6.5.

**Review by bebaps — COMMENTED** [review]
@mlsamuelson changes made, but GH doesn't seem to give me the option on this one to resolve your request.

**Review by mlsamuelson — APPROVED** [review]

**Pull request merged**
