### PR TITLE
Ws2 2322: Add the ability for .webp files to be uploaded as a image source

### PR DESCRIPTION
**Pull request by tbutterf**
### Description

Drupal 9.something introduced core support for webp images. So, all we needed to do was allow them on our image upload forms. I have updated the yamls associated with the forms that we use in our webspark design components via the webspark profile.

QA Steps:
To test this, simply go to any existing image on the site and try to replace it with a webp image. If it allows you to do it, it passes.

### Links

- [JIRA ticket](https://asudev.jira.com/browse/WS2-2322)

### Checklist

- [x] Design updates match [Web Standards](https://xd.adobe.com/view/56f6cb78-9af5-4b12-b4ce-ef319f71113f-03a5/) and [Unity Design System](https://unity.web.asu.edu)
- [x] Solution is documented on the Jira ticket
- [x] QA steps to verify have been included on the Jira ticket
- [x] No new PHP or JS errors
- [x] No accessibility issues are introduced with this update
- [x] Added/updated README.md files, if relevant
- [x] Confirm that any yaml files included have a matching update hook

### Verified in browsers 

- [x] Chrome
- [x] Safari
- [x] Firefox
- [x] Edge

### Screenshots

Note: Sections that are not applicable for this issue can be removed.

### CODE REVIEW

**Comment by mlsamuelson** [comment]
[Visit Site](https://pr-642-webspark-ci.pantheonsite.io/)

Created multidev environment [pr-642](https://dashboard.pantheon.io/sites/aec2f75f-35eb-41f8-abe7-95b292415259#pr-642) for webspark-ci.

**Review by bebaps — APPROVED** [review]
Tested and confirmed QA steps. Approving.

One question though, @tbutterf I cannot upload `webp` images in the CKEditor for use, but I can choose an existing `webp` image for use. This workaround is not a blocker for me, although I can see some people bringing it up in the future. Is it worth it to address now?

**Comment by tbutterf** [comment]
Ah. I hadn't thought to test it in CKEditor. Good catch! I'll look into it. Hopefully it's just a simple config change.

**Comment by bebaps** [comment]
Reviewed again and confirmed can now upload `webp` images in the CKE.

**Pull request merged**
