### PR TITLE
WS2-1653: Fixing testimonial carousel width.

### PR DESCRIPTION
**Pull request by juanmitriatti**
### Description

Testimonial Carousel content width not matching with the width of others Testimonials Component 

Solution: Removes uds-blockquote class padding when it's used into Testimonial Carousel.

### Links

- [JIRA ticket](https://asudev.jira.com/browse/WS2-1653)

### Checklist

- [ ] Design updates match [Web Standards](https://xd.adobe.com/view/56f6cb78-9af5-4b12-b4ce-ef319f71113f-03a5/) and [Unity Design System](https://unity.web.asu.edu)
- [ ] Solution is documented on the Jira ticket
- [ ] QA steps to verify have been included on the Jira ticket
- [ ] No new PHP or JS errors
- [ ] No accessibility issues are introduced with this update
- [ ] Added/updated README.md files, if relevant

### Verified in browsers 

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Screenshots

Note: Sections that are not applicable for this issue can be removed.

### CODE REVIEW

**Comment by mlsamuelson** [comment]
[Visit Site](https://pr-185-webspark-ci.pantheonsite.io/)

Created multidev environment [pr-185](https://dashboard.pantheon.io/sites/aec2f75f-35eb-41f8-abe7-95b292415259#pr-185) for webspark-ci.

**Comment by bebaps** [comment]
Reviewed the PR, but not merging yet. I think this is more likely a UDS issue. Left comments on the JIRA ticket.

**Comment by mlsamuelson** [comment]
Created https://asudev.jira.com/browse/UDS-1509 for verification on whether this is a WS2 or UDS issue to resolve.

**Review by mlsamuelson — CHANGES_REQUESTED** [review]
Need to merge the target branch back in and resolve the merge conflict please.

**Comment by mlsamuelson** [comment]
I created https://asudev.jira.com/browse/WS2-1855 to address removing local fixes after UDS fixes go in. Once the conflict is addressed, this can get a final review and then go in if approved.

**Review by mlsamuelson — APPROVED** [review]

**Pull request merged**
