### PR TITLE
WS2-2261: Implement separate downcast for editing and data views in tableCell

### PR DESCRIPTION
**Pull request by juanmitriatti**
#### Description of problem 
Since the WS2.12 update, tables that are in full html format text areas appear to be editable by anonymous users in the browser. This appears to be caused by the class "ck-editor__nested-editable" being added to every TD in the table. 

New tables and pre-existing tables are displaying this behavior, I suspect CK editor itself is adding the class
#### Solution 
Add editing downcast with contenteditable for table cells and 
a separate data downcast to exclude contenteditable attributes.

### Links

- [JIRA ticket](https://asudev.jira.com/browse/WS2-2261)

### Checklist

- [ ] Design updates match [Web Standards](https://xd.adobe.com/view/56f6cb78-9af5-4b12-b4ce-ef319f71113f-03a5/) and [Unity Design System](https://unity.web.asu.edu)
- [ ] Solution is documented on the Jira ticket
- [ ] QA steps to verify have been included on the Jira ticket
- [ ] No new PHP or JS errors
- [ ] No accessibility issues are introduced with this update
- [ ] Added/updated README.md files, if relevant
- [ ] Confirm that any yaml files included have a matching update hook

### Verified in browsers 

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Screenshots

Note: Sections that are not applicable for this issue can be removed.

### CODE REVIEW

**Comment by mlsamuelson** [comment]
[Visit Site](https://pr-595-webspark-ci.pantheonsite.io/)

Created multidev environment [pr-595](https://dashboard.pantheon.io/sites/aec2f75f-35eb-41f8-abe7-95b292415259#pr-595) for webspark-ci.

**Comment by tbutterf** [comment]
@juanmitriatti Can you please resolve the conflicts? Thanks!

**Comment by juanmitriatti** [comment]
> @juanmitriatti Can you please resolve the conflicts? Thanks!

Done @tbutterf

**Review by tbutterf — APPROVED** [review]
Nice work!

**Pull request merged**
