### PR TITLE
Ws2-1957: Behat testing Text Content (lists)

### PR DESCRIPTION
**Pull request by tbutterf**
### Description

Because lists are such basic building blocks of content, I took a very granular testing approach to these tests. I decided that the best thing to do would be to verify that what is displaying on the page matches what is in Unity. As such, I have used the "computed" values instead of relative values when determining things like sizes and widths etc. But, as long as our base for font size doesn't change, this should be okay.

I have written tests for the "View" tab, the "Edit" tab in CKEditor, and the Layout Builder version of CKEditor (in the OffCanvas dialog). The purposes of these test is to ensure that lists are displaying with the styles that we expect. This will help us know if a change somewhere along the line had cascading effects in the CSS that negatively affected our list styles.

When [UDS-1636](https://asudev.jira.com/browse/UDS-1636) lands we will need to tweak some of the margins, but that should be easy to do. It will also validate that this test really does work! 😄 

Also, I made this PR dependent on [WS2-2002](https://asudev.jira.com/browse/WS2-2002). So, it shouldn't be merged before that one, because it depends on the changes in that ticket for the styles it checks against.

I should also mention that this test expects to find specific fontawesome icons in the icon list. It specifically looks for a rocket, a bus, a car, and a bicycle. If it doesn't find those, it will fail. There is a ticket ([WS2-2012](https://asudev.jira.com/browse/WS2-2012)) that addresses the fact that we probably want to add a test for ASU Awesome icons in the icons lists, to make sure that they work. But, if that happens, we will need to update these tests as well. Basically, any time the `/text-content-lists` page's content changes, we will need to make sure it doesn't break these tests.

### Links

- [JIRA ticket](https://asudev.jira.com/browse/WS2-1957)

### Checklist

- [x] Design updates match [Web Standards](https://xd.adobe.com/view/56f6cb78-9af5-4b12-b4ce-ef319f71113f-03a5/) and [Unity Design System](https://unity.web.asu.edu)
- [x] Solution is documented on the Jira ticket
- [x] QA steps to verify have been included on the Jira ticket
- [x] No new PHP or JS errors
- [x] No accessibility issues are introduced with this update
- [x] Added/updated README.md files, if relevant

### Verified in browsers 

- [x] Chrome
- [x] Safari
- [x] Firefox
- [x] Edge

### Screenshots

Note: Sections that are not applicable for this issue can be removed.

### CODE REVIEW

**Review by mlsamuelson — CHANGES_REQUESTED** [review]
I pulled in the latest db from Dev and disabled the GTM and Cookie Consent and ran the test three times and all 3 times I had failures in the following:
```
--- Failed scenarios:

    features/text-lists.feature:7
    features/text-lists.feature:39
    features/text-lists.feature:81
```
The numbers are from the line number of the failed scenario.

If you cannot reproduce, ping me and we can take a look together.

**Comment by mlsamuelson** [comment]
[Visit Site](https://pr-414-webspark-ci.pantheonsite.io/)

Created multidev environment [pr-414](https://dashboard.pantheon.io/sites/aec2f75f-35eb-41f8-abe7-95b292415259#pr-414) for webspark-ci.

**Comment by bebaps** [comment]
Fixed merge conflicts, and simplified code per PHPStorm recommendations. After running tests, I got the same errors @mlsamuelson got. Looking further into the element computed values, I found that some expected CSS values did not match what the test was expecting. The values for `ulPaddingInlineStart === "32px"` and `liPaddingLeft === "32px"` did not match for me, likely causing the test failure.

@tbutterf Since you are doing a strict comparison here, it may be beneficial to update the `Exception` to tell the user which variable has the mismatched value to ease future troubleshooting.

**Comment by tbutterf** [comment]
@mlsamuelson and @bebaps Sorry about that. The error is coming because you need to compile the theme locally. It is automatically compiled in the CI, but for the styles to be correct, it needs to be compiled before you run this test. I'll look into improving the error handling.

**Review by mlsamuelson — APPROVED** [review]
Ah, makes sense about the compilation being needed. Should correct itself moving forward.

**Pull request merged**
