### PR TITLE
WS2 1994: 404 page shows error messages to anon user

### PR DESCRIPTION
**Pull request by tbutterf**
### Description

I couldn't find the source of this problem after several hours of investigation. So, instead of wasting more time trying to pinpoint the cause, I made a "band-aid" solution. Basically, I decided just to hide all messages on the 404 page for anonymous users.

UPDATED test instructions:

- Something changed so that the warning error isn't showing on every page load now, so, to test, you will need to pull this down to your local environment. Then, add `$links = NULL;` just before [line 172 in webspark_blocks.module](https://github.com/ASUWebPlatforms/webspark-ci/blob/f7fd0c31a4f3fb505b5bd38afbe54007f4b15c13/web/modules/webspark/webspark_blocks/webspark_blocks.module#L172), within the `if` statement. Then clear the cache and if you load any page while logged in as an admin, the error will re-appear. Then, go to the 404 page. You should see the error. Open the same page in an "incognito" window, and the error message should no longer display. If so, then this passes.

### Links

- [JIRA ticket](https://asudev.jira.com/browse/WS2-1994)

### Checklist

- [x] Design updates match [Web Standards](https://xd.adobe.com/view/56f6cb78-9af5-4b12-b4ce-ef319f71113f-03a5/) and [Unity Design System](https://unity.web.asu.edu)
- [x] Solution is documented on the Jira ticket
- [x] QA steps to verify have been included on the Jira ticket
- [x] No new PHP or JS errors
- [x] No accessibility issues are introduced with this update
- [x] Added/updated README.md files, if relevant

### CODE REVIEW

**Comment by mlsamuelson** [comment]
[Visit Site](https://pr-383-webspark-ci.pantheonsite.io/)

Created multidev environment [pr-383](https://dashboard.pantheon.io/sites/aec2f75f-35eb-41f8-abe7-95b292415259#pr-383) for webspark-ci.

**Review by mlsamuelson — COMMENTED** [review]
@tbutterf Did you consider that the error may be that the 404 page implements caching or cache tags that result in a cached copy generated for an admin user being shown in cached form for anonymous?  With debugging on, you could test that hypothesis.

If you've already considered that, ping me and I'll continue with the review of this PR.

**Comment by mlsamuelson** [comment]
@tbutterf Also note the merge conflict - which is for that WS2-1995 issue, which has now been merged.

**Comment by tbutterf** [comment]
@mlsamuelson Interestingly, something changed and now the warning I was getting is no longer happening. But, if I force it to happen by deleting a piece of code, I can get the error message to still display. I have checked for caching on that page, and I can't discover any. I have cleared the caches via Drush, as well as invalidated all cache contexts for that page, and yet the error message persists in displaying. When checking the caching, I have found the following:
image
image
From what I can tell, 404 pages are set to be "uncacheable."

**Review by mlsamuelson — APPROVED** [review]

**Pull request merged**
