### PR TITLE
[HOLD] [2.15.0] WS2-2249: Added custom focus on Anchor menu for accessibility

### PR DESCRIPTION
**Pull request by juanmitriatti**
#### Solution 
Added custom focus on Anchor menu for accessibillity

### Links

- [JIRA ticket](https://asudev.jira.com/browse/WS2-2249)

### Checklist

- [ ] Design updates match [Web Standards](https://xd.adobe.com/view/56f6cb78-9af5-4b12-b4ce-ef319f71113f-03a5/) and [Unity Design System](https://unity.web.asu.edu)
- [ ] Solution is documented on the Jira ticket
- [ ] QA steps to verify have been included on the Jira ticket
- [ ] No new PHP or JS errors
- [ ] No accessibility issues are introduced with this update
- [ ] Added/updated README.md files, if relevant
- [ ] Confirm that any yaml files included have a matching update hook

### Verified in browsers 

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Screenshots

Note: Sections that are not applicable for this issue can be removed.

### CODE REVIEW

**Comment by mlsamuelson** [comment]
[Visit Site](https://pr-554-webspark-ci.pantheonsite.io/)

Created multidev environment [pr-554](https://dashboard.pantheon.io/sites/aec2f75f-35eb-41f8-abe7-95b292415259#pr-554) for webspark-ci.

**Comment by juanmitriatti** [comment]
Hi @mlsamuelson 
I would like if we could ask Kathy to review this, particularly from a non-developer perspective.
Aside from the usual developer revision.

**Review by bebaps — CHANGES_REQUESTED** [review]
The code itself is not an issue, but I do think her expectation is still different from what this PR provides. Please see the video I uploaded to the PR ticket in JIRA.

**Comment by bebaps** [comment]
Had Kathy Marks review this, and she requested to put this ticket on hold for the time being.

**Comment by bebaps** [comment]
This was reviewed by Kathy and placed on hold. After more review on the JIRA ticket she concluded that there was something in the code preventing the default click behavior. There are `e.preventDefault` in this codebase, but it comes from the UDS side. I have also done work here, so this PR has grown stale and is unlikely to be merged in its current state. Closing the PR but will keep the branch alive for the time being.

**Pull request closed without merging**
