### PR TITLE
WS2-1595: Begin the process of porting the custom modules over

### PR DESCRIPTION
**Pull request by bebaps**
See: https://asudev.jira.com/browse/WS2-1595

This PR focuses only on the consolidation of modules, themes, and profiles into the core repository. The second portion of the JIRA ticket (Composer updates), shall be tackled in another PR to allow more team members to still test that particular functionality.

### CODE REVIEW

**Comment by mlsamuelson** [comment]
[Visit Site](https://pr-1-webspark-ci.pantheonsite.io/)

Created multidev environment [pr-1](https://dashboard.pantheon.io/sites/aec2f75f-35eb-41f8-abe7-95b292415259#pr-1) for webspark-ci.

**Comment by mlsamuelson** [comment]
I checked the modules/profiles/themes against what's in the `upstream-configuration/composer.json` and it matches 1:1. Same with the required packages, which are now alphabetized. I combed through and compared them and didn't find anything missing.

Once this builds successfully and the module/theme/profile folder names match their actual machine names instead of the repo names, I think this will be ready to go.

**Comment by mlsamuelson** [comment]
I made a commit to this branch to disable the testing jobs in the circleci/config.yml since those are being skipped, or throwing errors due to needing to be configured, and the work for those will be done as part of a future effort.

**Comment by bebaps** [comment]
NOTE: This PR is a bit messy, with all the commits being made to it after the PR was created. This is just a workflow change that we are not yet 100% used to, so in time, these PRs will be clean.

**Review by mlsamuelson — APPROVED** [review]
Obviously there's a lot here, but checking at the high level, comparing composer files and contents of the repo, it looks good. Additionally, tests out in the PR site. All requested tweaks were made.

**Pull request merged**
