### PR TITLE
WS2-1730: Layout Builder styles updates post-BS5

### PR DESCRIPTION
**Pull request by bebaps**
>  **This PR is now ready for review**

### Description

After completing the upgrade to BS5, the form styles in the Layout Builder were thrown off. 

### Links

- [JIRA ticket](https://asudev.jira.com/browse/WS2-1730)

### Notes

Also, there are three issues that I do not readily have a fix for that need to be surfaced to the team:

- For the media selection modal, the close button “X” icon is missing. This is because the markup for this from either core or Radix (?) has changed. **Update: solution has been proposed in another ticket.**
- Also, in the media selection modal, error colors are now incorrect. This is due to the updated form styles in UDS, and must be fixed on the UDS side. **Update: Will be addressed in new ticket.**
- In the Image Gallery block, the font sizes are different from any other block. This markup for this form appears to come from a completely different module than the rest, and also appears to be invalid. Where is this coming from, and how do we solve for it? This particular issue is also present in the current stable release of WS2. **Update: Will be addressed in new ticket.**

### CODE REVIEW

**Comment by mlsamuelson** [comment]
Agreed, this PR should address the
* Missing drag and drop icons for reordering multiple fields in the Layout builder
* Correct the background hover color on department names in the Web Directory Layout Builder form so there is adequate contrast.

For the missing dismiss modal icon, @tbutterf has a solution. Ticket created for this: https://asudev.jira.com/browse/WS2-1782 Travis will document the solution there.

Can you please elaborate on the incorrect color issue with the media selection modal form? Is it with the alerts? [Bootstrap provides more alert types and colors](https://getbootstrap.com/docs/5.0/components/alerts/) than UDS defines, and then Drupal has its own range of alert types, and so there's come consolidation and alignment of alert types across systems and rather than sort through all that, perhaps this one would be a good post-scrum to zero in on what the concern you've raise is. Not ticket created yet.

[Carousels and Galleries are defined in UDS](https://xd.adobe.com/view/56f6cb78-9af5-4b12-b4ce-ef319f71113f-03a5/screen/c4656960-099f-4e74-9f14-7647a5053621/specs/) separately from Cards. I did some spot-checking on font sizes and didn't find a discrepancy between UDS and the XD for those. The `component-carousel` component from Unity is loaded via the `asu_react_core` module. This should be part of a larger discussion about modernizing the `component-carousel` as a React app (it's currently a GlideJS implementation), and perhaps including it in the `components-core` package AND updating it to draw from the Cards contained in `components-core`. The cards change will have to be done in dialog with the Brand Team.  This is another post-scrum discussion.

**Comment by bebaps** [comment]
Reviewed the questions left by @mlsamuelson in post scrum, and all have been clarified.

**Comment by mlsamuelson** [comment]
UDS ticket to address the form field validation colors issue: https://asudev.jira.com/browse/UDS-1480

**Review by mlsamuelson — APPROVED** [review]

**Comment by mlsamuelson** [comment]
Updates look good. All other issues noted will take place in other tickets/prs.

**Pull request merged**
