### PR TITLE
WS2-1897: Added style for resize layout builder form

### PR DESCRIPTION
**Pull request by juanmitriatti**
#### Solution
Added style for resize layout builder form

### Links

- [JIRA ticket](https://asudev.jira.com/browse/WS2-1897)

### Checklist

- [ ] Design updates match [Web Standards](https://xd.adobe.com/view/56f6cb78-9af5-4b12-b4ce-ef319f71113f-03a5/) and [Unity Design System](https://unity.web.asu.edu)
- [ ] Solution is documented on the Jira ticket
- [ ] QA steps to verify have been included on the Jira ticket
- [ ] No new PHP or JS errors
- [ ] No accessibility issues are introduced with this update
- [ ] Added/updated README.md files, if relevant
- [ ] Confirm that any yaml files included have a matching update hook

### Verified in browsers 

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Screenshots

Note: Sections that are not applicable for this issue can be removed.

### CODE REVIEW

**Comment by mlsamuelson** [comment]
[Visit Site](https://pr-636-webspark-ci.pantheonsite.io/)

Created multidev environment [pr-636](https://dashboard.pantheon.io/sites/aec2f75f-35eb-41f8-abe7-95b292415259#pr-636) for webspark-ci.

**Review by bebaps — CHANGES_REQUESTED** [review]
@juanmitriatti This is an improvement, but still leaves empty space to the right of the Layout Builder. I notice this seems to only improve the experience to a certain point, if you make the LB large enough, it will eventually center itself like the current iteration.

Screenshot 2024-11-13 at 1 16 26 PM

**Comment by juanmitriatti** [comment]
Hi @bebaps 
Good morning!
I couldn’t reproduce this on Safari or Chrome on Mac. Could you share the screen size or steps to replicate it?

**Comment by mlsamuelson** [comment]
[Visit Site](https://pr-636-webspark-ci.pantheonsite.io/)

Created multidev environment [pr-636](https://dashboard.pantheon.io/sites/aec2f75f-35eb-41f8-abe7-95b292415259#pr-636) for webspark-ci.

**Comment by bebaps** [comment]
> Hi @bebaps Good morning! I couldn’t reproduce this on Safari or Chrome on Mac. Could you share the screen size or steps to replicate it?

@juanmitriatti I tested again after forcing a new build. It must have been something local on my end that was not compiling properly. On the multidev it works as expected. There is still some odd functionality, but I confirmed that Drupal core does the same odd stuff, so we have ammo in the future if someone reports this again we can just say no.

**Pull request merged**
