### PR TITLE
WS2-1913: added styles for invalid form field message

### PR DESCRIPTION
**Pull request by Bob-E**
### Description
While WS2-1744 fixed part of the issue with styling of invalid borders and the required dot. WS2-1913 addresses the invalid required FA icon and message.

Added css to web/themes/webspark/renovation/src/components/form-fields/_form-fields.scss 
Styles for forms with 'uds-form' and 'was-validated' classes:
  - Hide '.invalid-feedback' and adjacent '.invalid-feedback' for valid or invalid controls.
  - Show '.invalid-feedback' and adjacent '.invalid-feedback' for invalid controls.

### Links

- [JIRA ticket](https://asudev.jira.com/browse/WS2-1913)

### Checklist

- [x] Design updates match [Web Standards](https://xd.adobe.com/view/56f6cb78-9af5-4b12-b4ce-ef319f71113f-03a5/) and [Unity Design System](https://unity.web.asu.edu)
- [x] Solution is documented on the Jira ticket
- [x] QA steps to verify have been included on the Jira ticket
- [x] No new PHP or JS errors
- [x] No accessibility issues are introduced with this update

### Verified in browsers 

- [x] Chrome
- [x] Safari
- [x] Firefox
- [x] Edge

### Screenshots

image

Note: Sections that are not applicable for this issue can be removed.

### CODE REVIEW

**Comment by mlsamuelson** [comment]
[Visit Site](https://pr-446-webspark-ci.pantheonsite.io/)

Created multidev environment [pr-446](https://dashboard.pantheon.io/sites/aec2f75f-35eb-41f8-abe7-95b292415259#pr-446) for webspark-ci.

**Review by mlsamuelson — CHANGES_REQUESTED** [review]
package.json and yarn.lock have conflicting `unity-bootstrap-theme` numbers. 

Also,  is the issue from UDS-1699 and UDS-1686 the same? And can we avoid patching it in WS2 at all, and have UDS make the fix and then pull that in without requiring any scss of our own? I pinged you on https://asu-tech.slack.com/archives/C01ABUVU8LQ/p1717187356185489?thread_ts=1715645863.416139&cid=C01ABUVU8LQ to try and get to the bottom of this.

**Comment by tbutterf** [comment]
Is this a hotfix? Otherwise, it needs to have the merge base changed to be WS2-sprint-61.

**Comment by Bob-E** [comment]
@tbutterf I think the idea is to create this fix in UDS, and then reconcile it into Renovation. I'm just not sure how to close this PR out.

**Pull request closed without merging**
