### PR TITLE
WS2-2143: Uninstall imagick and modified configs

### PR DESCRIPTION
**Pull request by juanmitriatti**
#### Solution 
Uninstall imagick and modified configs

### Links

- [JIRA ticket](https://asudev.jira.com/browse/WS2-2143)

### Checklist

- [ ] Design updates match [Web Standards](https://xd.adobe.com/view/56f6cb78-9af5-4b12-b4ce-ef319f71113f-03a5/) and [Unity Design System](https://unity.web.asu.edu)
- [ ] Solution is documented on the Jira ticket
- [ ] QA steps to verify have been included on the Jira ticket
- [ ] No new PHP or JS errors
- [ ] No accessibility issues are introduced with this update
- [ ] Added/updated README.md files, if relevant
- [ ] Confirm that any yaml files included have a matching update hook

### Verified in browsers 

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Screenshots

Note: Sections that are not applicable for this issue can be removed.

### CODE REVIEW

**Comment by mlsamuelson** [comment]
[Visit Site](https://pr-508-webspark-ci.pantheonsite.io/)

Created multidev environment [pr-508](https://dashboard.pantheon.io/sites/aec2f75f-35eb-41f8-abe7-95b292415259#pr-508) for webspark-ci.

**Review by mlsamuelson — CHANGES_REQUESTED** [review]
The WS2 2.13.0 release is the one that adds the `imagick` module and now we're removing it. ... for all the new sites that will be updating, the removal isn't necessary. And we're adding numerous new yml files from https://github.com/ASUWebPlatforms/webspark-ci/pull/379/files that don't get cleaned up.

I'm wondering if we can do better...

The only sites currently that have `imagick` in them are our own... the Webspark CI site and any test upstreams we've created or updated. 

What if we reworked webspark_update_10004() so that it doesn't ever install the module - just comment out the contents of the update and mark it as deprecated. And then as much as possible reverse the changes (including the yml file additions from the original PR linked above)?  This would keep us from making unnecessary additions to our already huge yml file collection with configs we won't use. Will this break our CI and test upstream sites? If so, perhaps a series of drush commands that will clean things up can be put together so we can fix our sites with minimal effort.

**Comment by juanmitriatti** [comment]
The configurations called in **webspark_blocks_update_10002** are necessary to identify the "Rounded image".

**webspark_cropper_theme.install** was removed as it was unnecessary since it executed a Transparent config for Imagick.

**webspark_update_10004** was marked as deprecated because the installation of Imagick is not required.

**webspark_update_10006** was deleted because without installing Imagick, it is not necessary to uninstall it.

**Comment by mlsamuelson** [comment]
Thank you for the clarification about the field updates that were necessary. That makes sense and I appreciate you checking on that, @juanmitriatti .

**Review by mlsamuelson — CHANGES_REQUESTED** [review]
Almost there with this one. I discovered that the file is still getting loaded via Composer due to:
https://github.com/ASUWebPlatforms/webspark-ci/blob/WS2-2143-remove-imagick/upstream-configuration/composer.json#L33
and it is still referenced in the profile:
https://github.com/ASUWebPlatforms/webspark-ci/blob/WS2-2143-remove-imagick/web/profiles/webspark/webspark/webspark.info.yml#L101

**Comment by tbutterf** [comment]
Need to do this on any site that was using the imagick version of the round crop (only our internal sites) before applying this update. I have already done it on pr-508, dev, and test:
- drush config:set --input-format=yaml image.style.block_image_1_1_sml_rounded dependencies.module '[crop]'
- drush config:set --input-format=yaml image.style.block_image_1_1_med_rounded dependencies.module '[crop]'
- drush config:set --input-format=yaml image.style.block_image_1_1_lge_rounded dependencies.module '[crop]'
- drush pmu imagick

**Comment by tbutterf** [comment]
In testing this, something went wrong. It doesn't seem to work on a site that I updated from WS2 2.11.1. Investigating now.

**Review by mlsamuelson — APPROVED** [review]

**Comment by mlsamuelson** [comment]
I've run those commands against the `webspark-release-testing` environment.

Thanks both @juanmitriatti and @tbutterf .

**Pull request merged**
