### PR TITLE
Ws2 2308 rfi display

### PR DESCRIPTION
**Pull request by mlsamuelson**
### Description

RFI needed to implement checks for `rfiDisplay === true` before displaying the RFI when it's configured for a degree. 
This update aligns the admin UI for RFI blocks so programs that are not designated for display aren't displayed as options in the "Program of Interest" field. It also aligns us to match UDS with use of the `activeInDegreeSearch` filter. Additionally, we're updating the `app-rfi` component to the 2.4.0 version which incorporates use of the `rfiDisplay` in its logic as well.

### Links

- [JIRA ticket](https://asudev.jira.com/browse/WS2-2308)

### CODE REVIEW

**Comment by mlsamuelson** [comment]
[Visit Site](https://pr-596-webspark-ci.pantheonsite.io/)

Created multidev environment [pr-596](https://dashboard.pantheon.io/sites/aec2f75f-35eb-41f8-abe7-95b292415259#pr-596) for webspark-ci.

**Comment by mlsamuelson** [comment]
- Testing behavior for certificates - RFI should not display here and will emit message in browser console: https://pr-596-webspark-ci.ws.asu.edu/undergraduate-certificates/majorinfo/TSETMCERT/undergrad/true/119
- Testing behavior for major that has `rfiDisplay` set to false: https://pr-596-webspark-ci.ws.asu.edu/bachelors-degrees/majorinfo/BAEVEAMBA/undergrad/false/37
- Testing RFI config form - the `BAEVEAMBA` plancode should not appear in the options for "Program of Interest"

**Comment by mlsamuelson** [comment]
Tested and all three cases mentioned checked out.

**Review by bebaps — APPROVED** [review]
Approved.

**Pull request merged**
