### PR TITLE
Ws2 1578

### PR DESCRIPTION
**Pull request by Bob-E**
### Description of problem
H5 headings in the footer cause accessibility issues when heading levels are skipped.  

### Solution
Change H5 headings in the footer into DIVs with class=h5 to avoid headings being skipped. The h5 class retains all the same styles of the h5 tag. (don't use P tags b/c of max-width)

### Links

- [JIRA ticket](https://asudev.jira.com/browse/WS2-1578)

### Checklist

- [X] Design updates match [Web Standards](https://xd.adobe.com/view/56f6cb78-9af5-4b12-b4ce-ef319f71113f-03a5/) and [Unity Design System](https://unity.web.asu.edu)
- [X] Solution is documented on the Jira ticket
- [X] QA steps to verify have been included on the Jira ticket
- [X] No new PHP or JS errors
- [X] No accessibility issues are introduced with this update

### CODE REVIEW

**Comment by mlsamuelson** [comment]
[Visit Site](https://pr-136-webspark-ci.pantheonsite.io/)

Created multidev environment [pr-136](https://dashboard.pantheon.io/sites/aec2f75f-35eb-41f8-abe7-95b292415259#pr-136) for webspark-ci.

**Review by bebaps — CHANGES_REQUESTED** [review]
Your change looks good, but there are two things to address:

1. Please point your PR to merge into the `ws2-sprint-45` branch. You may need to pull in the code from there to prevent merge conflicts.
2. Testing the changes on the PR site, on the tablet breakpoint the footer menu no longer is centered. It is now left aligned, leaving extra space on the right margin area. Maybe some CSS just needs to be recompiled?

**Comment by Bob-E** [comment]
The paragraph tag's max-width was causing the footer menu to appear off-center. Replacing `p` with `div` remedies this.

**Comment by bebaps** [comment]
Reviewed, issues are resolved.

**Pull request merged**
