### PR TITLE
WS2-2276 update app-rfi component for ERFI updates

### PR DESCRIPTION
**Pull request by mlsamuelson**
### Description

Updates the `app-rfi` component to the latest version 2.3.12 to address WS2-2276 (updates for ERFI-150, ERFI-151, ERFI-152, ERFI-154, ERFI-156).

### Links

- [JIRA ticket](https://asudev.jira.com/browse/WS2-2276)

### Testing
Verify the RFI component loads without error and there are no noticeable regressions. We will be engaging with the ERFI stakeholders for UAT once this is in the Test environment, for thorough testing of the individual updates.

### CODE REVIEW

**Comment by mlsamuelson** [comment]
[Visit Site](https://pr-582-webspark-ci.pantheonsite.io/)

Created multidev environment [pr-582](https://dashboard.pantheon.io/sites/aec2f75f-35eb-41f8-abe7-95b292415259#pr-582) for webspark-ci.

**Comment by bebaps** [comment]
I see these errors preventing form submission when testing the Standalone RFI form here: https://pr-582-webspark-ci.pantheonsite.io/degree-pages/standalone-rfi

Is this expected when on its own? It's possible this test env is just missing needed configs. Also, the submit button background goes white on hover, is that intentional?

Screenshot 2024-09-11 at 12 35 13 PM
Screenshot 2024-09-11 at 12 34 50 PM

**Comment by mlsamuelson** [comment]
Submit button issue isn't with the UDS component, but with WS2, so I'm going to create a separate ticket for it. It's happening in the current stable release (2.13.1) so not a new regression.

**Comment by mlsamuelson** [comment]
Submit button issue, for reference: https://asudev.jira.com/browse/WS2-2293

**Review by bebaps — APPROVED** [review]
Tested, and the issues with the form appear resolved. Confirmed the submit button is WS2 only.

**Pull request merged**
