### PR TITLE
WS2-1535

### PR DESCRIPTION
**Pull request by Bob-E**
### Description of problem:
Using Layout builder and the 75/25 format, with a three card arrangement in the 75 container, the cards are not respecting the container size and expand into the right side quicklinks/navigation.

### Solution:
add `display: grid;` to the `.card-wrapper` class

### Links
- [JIRA ticket](https://asudev.jira.com/browse/WS2-1535)

### Checklist

- [x] Design updates match [Web Standards](https://xd.adobe.com/view/56f6cb78-9af5-4b12-b4ce-ef319f71113f-03a5/) and [Unity Design System](https://unity.web.asu.edu)
- [x] Solution is documented on the Jira ticket
- [x] QA steps to verify have been included on the Jira ticket
- [x] No new PHP or JS errors
- [x] No accessibility issues are introduced with this update
- [x] Added/updated README.md files, if relevant

### Verified in browsers

- [x] Chrome
- [x] Safari
- [x] Firefox
- [x] Edge

### Screenshots
Before style change:
image

After style:
image

Note: Sections that are not applicable for this issue can be removed.

### CODE REVIEW

**Comment by mlsamuelson** [comment]
[Visit Site](https://pr-194-webspark-ci.pantheonsite.io/)

Created multidev environment [pr-194](https://dashboard.pantheon.io/sites/aec2f75f-35eb-41f8-abe7-95b292415259#pr-194) for webspark-ci.

**Review by mlsamuelson — COMMENTED** [review]
This looks good once the merge conflict is dealt  with.

**Comment by Bob-E** [comment]
@mlsamuelson I think I merged that correctly. Hopefully, it's good to go now!

**Review by mlsamuelson — APPROVED** [review]
Looks good, @Bob-E . Thank you.

**Pull request merged**
