### PR TITLE
WS2-1646: Updated styles for the Inset box component

### PR DESCRIPTION
**Pull request by juanmitriatti**
### Description

Within the Inset box component, the text appears compressed on tablets devices.
Solution: Mobile styles were also applied on resolutions smaller than 768px (md).

### Links

- [JIRA ticket](https://asudev.jira.com/browse/WS2-1646)

### Checklist

- [ ] Design updates match [Web Standards](https://xd.adobe.com/view/56f6cb78-9af5-4b12-b4ce-ef319f71113f-03a5/) and [Unity Design System](https://unity.web.asu.edu)
- [ ] Solution is documented on the Jira ticket
- [ ] QA steps to verify have been included on the Jira ticket
- [ ] No new PHP or JS errors
- [ ] No accessibility issues are introduced with this update
- [ ] Added/updated README.md files, if relevant

### Verified in browsers 

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### CODE REVIEW

**Comment by mlsamuelson** [comment]
[Visit Site](https://pr-34-webspark-ci.pantheonsite.io/)

Created multidev environment [pr-34](https://dashboard.pantheon.io/sites/aec2f75f-35eb-41f8-abe7-95b292415259#pr-34) for webspark-ci.

**Comment by bebaps** [comment]
Reviewed and compared against the current website. Performed test on both a desktop and a mobile device. Looks good!

**Comment by bebaps** [comment]
@mlsamuelson this PR is good to go, but before I merged will this also require a PR to the UDS repo due to the changed files? Specifically `_inset-box.scss`?

**Comment by bebaps** [comment]
Had a quick convo with, @mlsamuelson confirmed we do not need a subsequent UDS PR. Merged and deleting branch.

**Pull request merged**
