### PR TITLE
WS2-2012: Update previously failing Behat tests

### PR DESCRIPTION
**Pull request by bebaps**
### Description

Some Behat tests were failing due to content in the DEV site being updated, and some test steps could no longer properly target the needed elements. This PR updates the element targeting where needed, and updates some steps in regards for pagination to be more flexible.

### Links

- [JIRA ticket](https://asudev.jira.com/browse/WS2-2012)

### Checklist

- QA steps to verify have been included on the Jira ticket

### CODE REVIEW

**Comment by mlsamuelson** [comment]
[Visit Site](https://pr-424-webspark-ci.pantheonsite.io/)

Created multidev environment [pr-424](https://dashboard.pantheon.io/sites/aec2f75f-35eb-41f8-abe7-95b292415259#pr-424) for webspark-ci.

**Review by mlsamuelson — APPROVED** [review]

**Review by mlsamuelson — CHANGES_REQUESTED** [review]
@bebaps Conflicts need to be resolved before this can be merged. Updates looked good and otherwise verified themselves.

**Comment by bebaps** [comment]
> @bebaps Conflicts need to be resolved before this can be merged. Updates looked good and otherwise verified themselves.

Merge conflicts resolved.

**Review by mlsamuelson — COMMENTED** [review]
Post humous approval.

**Pull request merged**
