### PR TITLE
WS2-2091: Update string URI generation for some React components

### PR DESCRIPTION
**Pull request by bebaps**
### Description

This PR applies a fix Travis came up with to resolve an issue with URLs being passed to React components.

### Links

- [JIRA ticket](https://asudev.jira.com/browse/WS2-2091)

### CODE REVIEW

**Comment by mlsamuelson** [comment]
[Visit Site](https://pr-452-webspark-ci.pantheonsite.io/)

Created multidev environment [pr-452](https://dashboard.pantheon.io/sites/aec2f75f-35eb-41f8-abe7-95b292415259#pr-452) for webspark-ci.

**Review by mlsamuelson — CHANGES_REQUESTED** [review]
toUriString() for for creating URIs instead of URLs. Not sure this is what we want.

Instead of https URLs, I'm getting routes, and the component isn't always updating like I'd expect - not sure what's up with that.
Screenshot 2024-05-31 at 4 46 24 PM

**Comment by tbutterf** [comment]
I think it's ready for a re-review.

**Comment by bebaps** [comment]
Reviewed the updates. Created a new page to test all Card types, and appears to be resolved now: https://pr-452-webspark-ci.ws.asu.edu/test-pr-452

@mlsamuelson if good on your end, I think this can now be merged.

**Review by mlsamuelson — APPROVED** [review]

**Pull request merged**
