### PR TITLE
Ws2 1629 - Composer file updates/deletions

### PR DESCRIPTION
**Pull request by bjdevil21**

### CODE REVIEW

**Comment by mlsamuelson** [comment]
[Visit Site](https://pr-20-webspark-ci.pantheonsite.io/)

Created multidev environment [pr-20](https://dashboard.pantheon.io/sites/aec2f75f-35eb-41f8-abe7-95b292415259#pr-20) for webspark-ci.

**Review by mlsamuelson — CHANGES_REQUESTED** [review]
PR should be against current sprint branch, not `master`

**Comment by bjdevil21** [comment]
I've added the composer.lock deletion to this PR now (after our brief post-scrum today). Also, instead of a separate ticket (and another credit-burning CI build), I also slipped in some "pork barrel amendments" to this PR by updating a couple of require-dev libraries I caught.

**Comment by bjdevil21** [comment]
@bebaps - I requested you as the approver because some of the changes I made here in the Composer files will be git conflicts. (At least the composer.lock file just needs to be deleted.)

**Comment by bjdevil21** [comment]
I just rebuilt this PR to remove some Mac newlines and squash the version changing commits.

**Pull request closed without merging**
