### PR TITLE
DO NOT MERGE - WS2-1834: Added Cropped rounded (1:1) media

### PR DESCRIPTION
**Pull request by juanmitriatti**
### Links

- [JIRA ticket](https://asudev.jira.com/browse/WS2-1834)

### Checklist

- [ ] Design updates match [Web Standards](https://xd.adobe.com/view/56f6cb78-9af5-4b12-b4ce-ef319f71113f-03a5/) and [Unity Design System](https://unity.web.asu.edu)
- [ ] Solution is documented on the Jira ticket
- [ ] QA steps to verify have been included on the Jira ticket
- [ ] No new PHP or JS errors
- [ ] No accessibility issues are introduced with this update
- [ ] Added/updated README.md files, if relevant

### Verified in browsers 

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Screenshots

Note: Sections that are not applicable for this issue can be removed.

### CODE REVIEW

**Comment by juanmitriatti** [comment]
QA Steps: 

1. Add Image block
2. Add media and select Cropped image rounded (1:1)

**Comment by mlsamuelson** [comment]
Wait on https://asudev.jira.com/browse/UDS-1581 to be resolved so we can apply the 1:1 crop on cards as well as blocks.

**Comment by mlsamuelson** [comment]
We decided on this task that WS2 should handle the round image handling in the media settings, but we don't want put any responsibility on UDS to handle or create round images.

Please let me know if you have any questions or would like to review this one together, @juanmitriatti

**Comment by mlsamuelson** [comment]
Closing.

**Pull request closed without merging**
